### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by WindowsNT** [githole/Live-Coder#6]
I 'd love to include this in my video sequencer, perhaps you can support a license such as MIT?

**Comment by bernatferragut** [comment]
Which exactly?

**Comment by githole** [comment]
I've released under MIT license, like any other software in my repository.
(Simply I forgot to give license)
https://github.com/githole/Live-Coder/commit/fe09ddfdb22e128682a2dec19d2fadacbcbdc12e
